Avoid applying eComscan to archived repositories
mage-os/terraform pull request #103
Opened 2024-12-30 10:18 UTC by fballiano

When TF tried to apply eComscan to all repos, it fails when the repo is archived (readonly).

This PR should fix that.

2024-12-30 10:48 UTC, DavidLambauer approved these changes

2024-12-30 10:52 UTC, fballiano commented
sorry @DavidLambauer I had to add one more commit to fix a whitespace issue :-(

2025-01-02 06:59 UTC, sprankhub requested changes

2025-01-02 06:59 UTC, sprankhub commented on main.tf
> +          ref: ${{ github.event.pull_request.head.sha }}
Please check https://github.com/mage-os/terraform/actions/runs/12545518588/job/34979848888?pr=103. There seems to be an issue with this. I think we either need to use `${` or `$${{`.

2025-01-02 10:52 UTC, fballiano commented on main.tf
> +          ref: ${{ github.event.pull_request.head.sha }}
this escaping is very confusing to me, I'm not sure the new committed version is ok in all parts

2025-01-02 12:15 UTC, sprankhub approved these changes

2025-01-02 12:16 UTC, merged